### ISSUE TITLE
Missing variables from JRA55-do

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/master_index#11]
From https://github.com/COSIMA/cosima-cookbook/issues/207#issuecomment-817520137

> The cookbook default database is missing these variables from /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/:

> areacella, sftof from atmos/fx
> tos, areacello, sos, uos, vos (i.e. everything in ocean)
> siconc, siconca (i.e. everything in seaIce)

> Could they be added please? I'm most interested in the last 2, but I imagine all of them could be useful at some point.

**Comment by aidanheerdegen** [comment]
The scripts for generating the symbolic links are not under version control. Not sure if I should bother making them proper repos on their own right, but in the meantime ... this is what it currently looks like:
```
DATADIR=/g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/
  
mkdir -p atmos land ice

for v in rsds rlds prra prsn
do
  mkdir -p atmos/${v}
  ln -s ${DATADIR}/atmos/3hr/${v}/gr/v20190429/*.nc atmos/${v}/.
done

for v in psl tas huss uas ts vas
do
  mkdir -p atmos/${v}
  ln -s ${DATADIR}/atmos/3hrPt/${v}/gr/v20190429/*.nc atmos/${v}/.
done

v=licalvf
mkdir -p ice/${v}
ln -s ${DATADIR}/landIce/day/licalvf/gr/v20190429/*.nc ice/${v}/.

v=friver
mkdir -p land/${v}
ln -s ${DATADIR}land/day/friver/gr/v20190429/*.nc land/${v}/.
```

Changed to
```
DATADIR=/g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0

# Atmosphere
realm=atmos
mkdir -p ${realm}
for v in areacella sftof
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/fx/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done

for v in rsds rlds prra prsn
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/3hr/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done

for v in psl tas huss uas ts vas
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/3hrPt/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done


# Ice (actually landIce: should maybe fix this)
realm=ice
mkdir -p ${realm}

v=licalvf
mkdir -p ${realm}/${v}
ln -s ${DATADIR}/landIce/day/licalvf/gr/v20190429/*.nc ice/${v}/.


# Land
realm=land
mkdir -p ${realm}

v=friver
mkdir -p ${realm}/${v}
ln -s ${DATADIR}/${realm}/day/friver/gr/v20190429/*.nc land/${v}/.


# Ocean
realm=ocean
mkdir -p ${realm}

for v in areacello
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/fx/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done

for v in tos
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/day/${v}/gn/v20190429/*.nc ${realm}/${v}/.
done

for v in sos
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/monC/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done

for v in uos vos
do 
  mkdir -p ${realm}/${v}
  ln -s ${DATADIR}/${realm}/yrC/${v}/gr/v20190429/*.nc ${realm}/${v}/.
done
```

**Comment by aidanheerdegen** [comment]
@aekiss I have updated the symbolic links in `/g/data/ik11/inputs/JRA-55/MRI-JRA55-do/MRI-JRA55-do-1-4-0` and re-run the database build.

Can you check the variables you requested are present and correct, and if so close the ticket.

**Comment by aekiss** [comment]
Thanks for the quick turnaround @aidanheerdegen. 
`siconc`, `siconca` are still missing, i.e. everything in
`/g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-4-0/seaIce`

**Comment by aidanheerdegen** [comment]
Doh. Thanks. I've added them. The indexing is running, should take about 10 minutes. Can you check again in half an hour, same pack-drill as before.

**Comment by aekiss** [comment]
Great, thanks, it all looks good now.
