### ISSUE TITLE
Incorrect YAML in metadata

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/master_index#12]
There is incorrect YAML syntax in a `metadata.yaml` file:

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/COSIMA%2FCC-Database%20Build/detail/CC-Database%20Build/307/pipeline#log-339

@hakaseh this is `/g/data/ik11/outputs/access-om2/1deg_jra55_iaf_omip2dEdd_cycle1/metadata.yaml`

You can use tools like https://codebeautify.org/yaml-validator to validate your YAML files. In this case it is the excessive indentation
```
description: >-
        --> same as 1deg_jra55_iaf_omip2femip_cycle1, except shortwave = dEdd in ice/cice_input.nml.
  1 degree ACCESS-OM2 global model configuration under interannual forcing.
```
on line 5 that it doesn't like. If you remove it then it seems to parse ok, so this works:
```
description: >-
  --> same as 1deg_jra55_iaf_omip2femip_cycle1, except shortwave = dEdd in ice/cice_input.nml.
  1 degree ACCESS-OM2 global model configuration under interannual forcing.
```
not sure it is a great idea to use `-->` though. What does it mean?

**Comment by hakaseh** [comment]
@aidanheerdegen thanks for reporting the error. I am obviously not familiar with yaml syntax. I just fixed the metadata.yaml, and it should be valid now?

I usually use --> as right-arrow, and in this case as a bullet point ➡️ no special meaning 😅

**Comment by aidanheerdegen** [comment]
That seems to have worked

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/COSIMA%2FCC-Database%20Build/detail/CC-Database%20Build/317/pipeline#log-338

and the new metadata is showing up in the explorer. 

I'll close this.
