### ISSUE TITLE
index 01deg_jra55v140_iaf_cycle4

### ISSUE THREAD

**Issue by aekiss** [COSIMA/master_index#20]
`01deg_jra55v140_iaf_cycle4` is being temporarily stored at `/g/data/cj50/admin/incoming/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4` until we find the SUs to fill in the deleted ice data, after which I plan to move it to `/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4`. However it might take several months to fill in the ice data, so in the meantime it would be good to index it so it can be used.

This supersedes `/g/data/ik11/outputs/access-om2-01/01deg_jra55v140_iaf_cycle4` - should I delete that now to avoid confusing the db?

**Comment by aidanheerdegen** [comment]
Um, I think we did think this was a possibility, but the `admin` directory is not publicly accessible, so the data can't be indexed in that location.

**Comment by aekiss** [comment]
oh yeah. oops. I'll see if I can come up with a better plan.

**Comment by aekiss** [comment]
maybe I should `mkdir /g/data/cj50/interim` and use that?
Not sure if we are liberty to do what we want in`/g/data/cj50` but I'm waiting to hear back from Yiling.

**Comment by aekiss** [comment]
this is now unnecessary, as I've moved the data to
`/g/data/cj50/access-om2/raw-output/access-om2-01/01deg_jra55v140_iaf_cycle4`
which is already indexed
