### ISSUE TITLE
Offline DB updates

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/master_index#24]
## Introduction

Offline DB updates are a solution to https://github.com/COSIMA/master_index/issues/22

Where `DBdir=/g/data/ik11/databases` and `$DBdir/cosima_master.db` is a symbolic link to the latest update of the DB.

## Proposal

1. Copy current DB to a temporary location (should be a different location or hidden so no user attaches accidentally)
2. Update new version
3. Copy updated DB to time-stamped filename in `$DBdir` (or subdirectory)
4. Change symbolic link to point to updated DB file
5. Delete older versions of DB no longer required (see Backup Strategy)

## Backup Strategy

1. Retain **at least** previous version of DB so current sessions remain alive (preference might be a week of previous updates for safety)
2. Keep regular snapshots, maybe weekly for a month

## Comments

Changing a symbolic link does no affect current connections. I have tested this. 

With a local version of the master database:
```bash
$ ls -l
total 5364764
-rwxr-x--- 1 aph502 v45       1372 May 26 16:20 build_master_index
-rw-r----- 1 aph502 v45 5493440512 Jun  1 02:42 cosima_master.db
-rw-r----- 1 aph502 v45        359 May 19  2021 index.py
lrwxrwxrwx 1 aph502 v45         16 Jun  9 15:33 link.db -> cosima_master.db                                                                   
drwxr-x--- 2 aph502 v45      49152 Jun  1 02:42 logs
-rw-r----- 1 aph502 v45        480 May 10 14:17 README.md
-rwxr-x--x 1 aph502 v45        430 May 31 20:56 update_db.py
```

Opening a connection and querying works as you would expect
```python
In [3]: session = cc.database.create_session('link.db')
                                                       
In [4]: cc.querying.get_experiments(session)           
Out[4]:                                                
                                    experiment  ncfiles
0                                        woa18       24
1                                 eac-zstar-v1       29
2                                 eac-zstar-v2       76
3           025deg_jra55_ryf9091_gadi_norediGM      312
4               025deg_jra55_ryf9091_gadi_noGM      316   
..                                         ...      ...                    
155  1deg_jra55_SAMextr_ryf0203_from9091_kds50     3875                    
156                 01deg_jra55v140_iaf_cycle3    22300
157                1deg_jra55v13_ryf8485_RCP45     2100
158                1deg_jra55v13_ryf0304_RCP45     2544
159               1deg_jra55v13_ryf8485_spinup     4000
                        
[160 rows x 2 columns]
```
then change symbolic link to point at a random file
```bash
$ ln -fs README.md link.db                                                                                 
$ ls -l
total 5364764
-rwxr-x--- 1 aph502 v45       1372 May 26 16:20 build_master_index
-rw-r----- 1 aph502 v45 5493440512 Jun  1 02:42 cosima_master.db
-rw-r----- 1 aph502 v45        359 May 19  2021 index.py
lrwxrwxrwx 1 aph502 v45          9 Jun  9 15:37 link.db -> README.md
drwxr-x--- 2 aph502 v45      49152 Jun  1 02:42 logs
-rw-r----- 1 aph502 v45        480 May 10 14:17 README.md
-rwxr-x--x 1 aph502 v45        430 May 31 20:56 update_db.py
```
`session` still works fine, even though it internally the `url` is no longer pointing to the DB file
```python
In [24]: cc.querying.get_experiments(session)
Out[24]: 
                                    experiment  ncfiles
0                                        woa18       24
1                                 eac-zstar-v1       29
2                                 eac-zstar-v2       76
3           025deg_jra55_ryf9091_gadi_norediGM      312
4               025deg_jra55_ryf9091_gadi_noGM      316
..                                         ...      ...
155  1deg_jra55_SAMextr_ryf0203_from9091_kds50     3875
156                 01deg_jra55v140_iaf_cycle3    22300
157                1deg_jra55v13_ryf8485_RCP45     2100
158                1deg_jra55v13_ryf0304_RCP45     2544
159               1deg_jra55v13_ryf8485_spinup     4000

[160 rows x 2 columns]

In [25]: session.bind.url
Out[25]: sqlite:///link.db
```
So `session.bind.url` is for information only. The open file descriptor must point to the original file.

It is probably a good idea to manually resolve the symlink so that this information is consistent with the information contained in the session.

https://github.com/COSIMA/cosima-cookbook/issues/288

Step 1 of proposed strategy requires a copy of the DB so the copy can be updated. The [SQLite docs have some instructions for backups](https://www.sqlite.org/backup.html), so definitely the fastest is lock the DB and copy, but there is an inbuilt `.clone` command which took 5 minutes to backup up a 5.2G DB
```
$ time sqlite3 cosima_master.db ".clone clone.db"                                                          
experiments... done
keywords... done
ncattribute_strings... done
variables... done
keyword_assoc... done
ncfiles... done
ncvars... done
ncattributes... done
ix_experiments_experiment_rootdir... done
ix_keywords__keyword... done
ix_variables_name... done
ix_variables_name_long_name_units... done
ix_ncfiles_ncfile... done
ix_ncfiles_experiment_id... done
ix_ncfiles_experiment_ncfile... done
ix_ncvars_ncfile_id... done
ix_ncattributes_ncvar_id... done

real    5m54.924s
user    2m21.944s
sys     0m39.638s
$ ls -lrth *.db
-rw-r----- 1 aph502 v45 5.2G Jun  1 02:42 cosima_master.db
-rw-r----- 1 aph502 v45 5.0G Jun  9 16:30 clone.db
```
I had a session open the whole time on `cosima_master.db`, and could access the DB during the process. Sometimes there was a slight delay, but fractions of a second, so it seems a decent way to clone the DB with minimal impact to users. Strangely the clone was smaller, perhaps it manages slightly more efficient packing of data in the copy?

I got the information on `.clone` from https://database.guide/clone-sqlite-database/

**Comment by aidanheerdegen** [comment]
Timing for a simple copy for comparison
```bash
$ time cp cosima_master.db tmp.db

real    0m24.029s
user    0m0.000s
sys     0m11.133s
```

**Comment by aekiss** [comment]
If step 3 is a copy (not a move) there won't be any need for step 1 (except the firs time), since it will be the same as the latest so can be updated.

**Comment by aekiss** [comment]
Might be good to set file permissions for the timestamped DB copy in `$DBdir` to read-only to make it clear that the live DB is never to be updated.

**Comment by aekiss** [comment]
This approach of separating the writable DB from the read-only user-facing DB also provides an opportunity for other steps between 2 and 3, e.g. a DB integrity check before making it live.

**Comment by aekiss** [comment]
for step 5, maybe do something like this, so the DB won't be deleted if it's been read in the past 14 days (also ensuring it won't be deleted if currently in use)
```
find $DBdir/cosima_master_????-??-??*.db -type f -atime +14 -exec rm {} \;
```

**Comment by micaeljtoliveira** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite generation of DB](https://trello.com/c/Sq2O01Gz/2-rewrite-generation-of-db)
