### ISSUE TITLE
Scan for incorrect permissions

### ISSUE THREAD

**Issue by aidanheerdegen** [COSIMA/master_index#27]
On occasion indexing fails because of incorrect permissions on files and directories in the shared spaces under `ik11` and `cj50`.

Would be good to have a jenkins job running to check for incorrect permissions.

**Comment by micaeljtoliveira** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add pipeline to check file permissions](https://trello.com/c/VTAChqBS/6-add-pipeline-to-check-file-permissions)

**Comment by micaeljtoliveira** [comment]
@aidanheerdegen ICould you clarify a bit the problem: is the issue the group ownership (gid is not `ik11` of `cj50`) or the actual permissions (group does not have permission to read the files)? Or maybe both?

**Comment by aidanheerdegen** [comment]
Both. Though they can sometimes end up with the some similar symptoms, so a file or directory with group `rx` but with a group not all users belong to is effectively not group readable/executable.

But also just the wrong group is bad from an accounting point of view. Files are accounted for by the group of the file, not their physical location. So being owned by a the wrong project will lead to them being accounted for under that other project quota. This is undesirable.

**Comment by aekiss** [comment]
re. accounting by group: NCI seem to be progressively phasing this out in favour of accounting by location https://opus.nci.org.au/pages/viewpage.action?pageId=165609537
