### ISSUE TITLE
Output files permissions

### ISSUE THREAD

**Issue by navidcy** [COSIMA/master_index#9]
Recently I came across an issue where I was creating my own database but some of the output files from the experiment I wanted did not have appropriate permission to be readable by all `ik11` users.

I suggest that, before `master_index` builds the default database every night, perhaps it's a good idea to make sure that all files in `ik11/output` are readable by all `ik11` users? Is this not a good idea? Better alternatives?

@aidanheerdegen, @AndyHoggANU, @angus-g

**Comment by micaeljtoliveira** [comment]
@navidcy Something along these lines has been implemented some time ago (an email is sent to owners of files with incorrect permissions on a weekly basis). Plus, there are now some tools to help users check and fix the permissions of their files (see https://github.com/COSIMA/master_index/wiki )

Do you think this is enough to have this issue closed?
